# LISTS 

loc_by_series = {'TOS': ['USS ENTERPRISE', 'bridge', 'KIRKS quarters',
                         'RIGEL XII', 'TALOS IV', '892 IV',   
                         'engineering', 'vulcan', 'mirror universe',
                         'ALDEBARAN III', 'ALPHA 117', 'ALPHA CARINAE II',
                         'ALPHA CARINAE V', 'ALPHA ERIDANI II', 'ALPHA III', 
                         'ALPHA MAJORIS I', 'Alpha V2', 'Altair VI',
                         'Altamid', 'Amusement Park Planet', 'Antos IV',
                         'Ardana', 'Argana II', 'Argelius II', 
                         'Argus X', 'Ariannus', 'Arreta',  'Axanar',
                         'babel', 'Benecia', 'Berengaria VII', 
                         'Beta Antares IV', 'Beta III', 'Beta VI', 
                         'Beta XII-A', 'Camus II', 'Canopus planet', 
                         'Capella IV', 'Catualla', 'Cestus III',
                         'Ceti Alpha V', 'Ceti Alpha V', 'Cheron', 
                         'Coridan', 'Corinth IV', 'Cygnet XIV', 'Daran V', 
                         'Davlos II', 'Delta Vega', 'Deneb II', 
                         'Deneb V', 'Deneva'],
                'TNG': ['ACAMAR III', 'USS ENTERPRISE NCC 1701-D',
                        'TEN FORWARD', 'ADELPHOUS IV', 'ALDEA', 
                        'ALGERON IV', 'ALPHA CYGNUS IX', 'ALPHA MOON', 
                        'Alpha Omicron VII', 'Alpha Onias III', 
                        'Altair III', 'Altec', 'Alture VII', 
                        'ANGEL ONE', 'Angosia III', 'Antede III',
                        'Antica', 'Archer IV', 'Arcturus IV',
                        'Arkaria', 'Arloff IX', 'Armus IX', 'Arvada III', 
                        'Atalia VII', 'audet IX', 'baku', 'Barkon IV', 
                        'Barradas III', 'Barson II', 'Barzan II', 
                        'Beltain IX', 'Benzar', 'Bersallis III', 
                        'Beta Agni II', 'Beta Kupsic', 'Beta Moon', 
                        'Beta Thoridar', 'Betazed', 'Beth Delta I', 
                        'Bilana III', 'Bokara VI', 'Bolarus IX', 
                        'Boraal II', 'Boradis III', 'Boreal III', 
                        'Bracas V', 'Braslota II', 'Brekka', 
                        'Brentalia', 'Bringloid V', 'Browder IV', 
                        'Bynaus', 'Caere IV', 'Cairn', 'Calder II', 
                        'Caldos IV', 'Camor V', 'Cardassia', 'Carema III',
                        'Carraya IV', 'Castal I', 'Celes II', 
                        'Celtris III', 'Cerberus II', 'Chalna', 
                        'Chandra V', 'Chantil III', 'Chaya VII', 
                        'Chrysalia', 'Cirrus IV', 'Corvan II'
                        'Coltar IV', 'Cor Caroli V', 'Daled IV', 
                        'Danula II', 'Deinonychus VII', 'Delinia II', 
                        'Delos IV', 'Delta IV', 'Delta Rana IV', 
                        'Deneb IV', ''],
                'DS9': ['Boranis III', 'Bopak III', 'Bolias', 'Blue Horizon', 'ADARAK', 'PROMENADE', 'HABITAT RING',
                        'CARDASSIA', 'BAJOR', 'CARGO BAY', 
                        'OBRIENS QUARTERS', 'ARBORETUM', 
                        'ADIGEON PRIME', 'AJILON PRIME', 
                        'Altair IV', 'Amleth Prime', 'Andevian II',
                        'Andros III', 'ANDORIA', 'AR-558', 
                        'Archanis IV', 'Arcybite', 'Argratha', 
                        'Atbar Prime', 'Athos IV', 'Atifs IV', 
                        'Atrea IV', 'Avenal VII', 'bajor', 
                        'bajor VII', 'bajor VIII',
                        'bajoran lunar V', 'Balancar', 
                        'Balosnee VI', 'Barisa Prime', 'Betazed',
                        'Boreth', 'Brax', 'Breel IV', 'Brinda IV', 
                        'Bryma', 'Caleb IV', 'Callinon VII', 
                        'Calondia IV', 'Campor III', 'Cardassia', 
                        'Cardassia III', 'Cardassia IV', 
                        'Cardassia Prime', 'Cardassia V', 
                        'Casperia Prime', 'Davlos III', 'Davlos Prime', 
                        'Dayos IV', 'Decos Prime', ''],
                'VOY': ['Banea', 'Avery III', '1865 ALPHA', 'USS VOYAGER', 'AKRITIRI',
                        'ALASTRIA', 'ALPHA 441', 'Arakis Prime', 
                        'Argala', 'Aschelan V', 'Benthos', 'Caldik Prime', 
                        'Chaltok IV', 'the continuum', 'Dedestris', 
                        'Delios VII', ''],
                'ENT': ['AGARON', 'Andor', 'Andoria', 'Archers Planet',
                        'Azati prime', 'BSaari II', 'Burala prime',
                        'Dakala', 'Dekendi III', 'Delb II',
                        'Deneva prime'],
                'DSC': [],
                'PIC': [],
                'LD' : []}

series = {
          'ALL': ['a', 'b', 'c', 'd'],
          'OLD': ['old_a', 'old_b', 'old_c', 'old_d'],
          'NEW': ['new_a', 'new_b', 'new_c', 'new_d'],
          'TOS': ['tos_a', 'tos_b', 'tos_c', 'tos_d'],
          'TNG': ['tng_a', 'tng_b', 'tng_c', 'tng_d'],
          'DS9': ['DS9_A', 'DS9_B', 'DS9_C', 'DS9_D'],
          'VOY': ['VOY_A', 'VOY_B', 'VOY_C', 'VOY_D'],
          'ENT': ['ent_a', 'ent_b', 'ent_c', 'ent_d'],
          'DSC': ['dsc_a', 'dsc_b', 'dsc_c', 'dsc_d'],
          'PIC': ['pic_a', 'pic_b', 'pic_c', 'pic_d'],
          'LD' : ['ld_a', 'ld_b', 'ld_c', 'ld_d']
          }


char_by_series = {'TOS':['GORN', 'RAEL', 'TYLER', 'MELKOT', 
                         'CLOUD', 'WENCH', 'HUMANOID',  'BOB', 
                         'KLINGON', 'ROBERTA', 'MARLA', 'PIPER',
                         'BENTON', 'COCHRANE', 'MARTA',  'BEN', 
                         'MARVICK', 'HUMBOLDT', 'GOSSETT','ADAMS',
                         'DICKERSON', 'MIRAMANEE', 'MARTHA', 'MARY',
                         'COMM', 'THASIAN', 'DEHNER', 'NORMAN', 
                         'KARA', 'MARA', 'WEBB', 'KAZ','ELIZABETH',
                         'KIRK2', 'LEUITENANT NYOTA UHURA', 'BALOK', 
                         'JANICE', 'GUARDS', 'ORACLE',  'DEELA',
                         'CROMWELL', 'CHRIS', 'CRATER', 'PRISONERS',  
                         'TEPO', 'YUTAN', 'FOX', 'DRAIN', 'TANNOY',  
                         'ELAAN', 'LINCOLN', 'VULCAN', 'PALMER', 
                         'TALOSIAN', 'VINA',  'SARAH', 'COLONEL', 
                         'ZABO', 'WASHBURN', 'KORBY', 'LESLIE', 
                         'HASKINS', 'WOMAN', 'BEING', 'JOACHIM', 
                         'HANSEN','MIRA','LINKE', 'BAILEY', 'KALO', 
                         'ONEIL', 'AREX', 'MAXIMUS', 'COMPANION', 
                         'MARPLON', 'EVE', 'ADMINISTRATOR', 'NURSE', 
                         'CHILDREN', 'CORY', 'MAGDA', 'DARAS', 
                         'HUSBAND', 'ELASIAN', 'CREWWOMAN',
                         'SUB COMMANDER', 'DECKER', 'APRIL', 
                         'THERAPIST', 'HELMSMAN', 'DRAMIAN', 
                         'MASTERS', 'WILSON', 'DEVNA', 'ROMULAN', 
                         'APELLA', 'SENTINEL', 'CAROLYN', 'ALEXANDER',
                         'RILEY', 'BARMAN', 'JARIS', 'NOMAD', 'TINA',
                         'CARTER', 'ATKINS', 'TEACHER', 'KAPLAN', 
                         'PAVEL ANDREIEVICH CHEKOV', 'THANN', 
                         'KAHLESS', 'COMPUTER', 'JAHN', 'AURELAN', 
                         'HODIN', 'EM3GREEN', 'ZAHRA', 'SARGON', 
                         'FINNEGAN', 'CADMAR', 'SCHMITTER', 'ANAN', 
                         'DROXINE', 'HANAR', 'SECURITY', 'ENERGY', 
                         'MELAKON', 'RODRIQUEZ', 'POLICEMAN',
                         'CHEIF ENGINEER SCOTTY', 'RAMART', 'NONA',
                         'TELEPATH', 'TECHNICIAN', 'BATES', 'BELE', 
                         'CAPTAIN JAMES (JIM) KIRK','SHAW',
                         'MAJOR', 'GELDER', 'HELM', 'GARROVICK', 
                         'SEVRIN', 'APPEL', 'MAKORA', 'KHAN', 
                         'DOCTOR LEONARD MCCOY (BONES)', 'SYBOK',
                         'TAMULA', 'EKOR', 'LAWGIVER', 'UND',
                         'ENWRIGHT', 'FINNEY', 'PROBE', 'TRACEY', 
                         'TABLE', 'BRENT', 'ERACLITUS', 'MBENGA',
                         'KEVIN', 'THELIN', 'GALWAY', 'ANGELA', 
                         'MEN', 'DAVISON', 'WALLACE', 'JACKSON', 
                         'HEAD', 'VEER', 'KARIDIAN', 'REGER', 'TAU', 
                         'GAV', 'METRON', 'LIEUTENANT', 'PITCAIRN',
                         'MITCHELL', 'GUARD', 'CREW', 'LORA', 'SWITCH', 
                         'SINGH', 'MORGAN', 'GALT', 'ODONA', 'OFFICER',
                         'RAND', 'GAETANO', 'ENSIGN', 'ROJAN', 'MAN', 
                         'SHEAR', 'CHILDRESS', 'OXMYX', 'MUDDS', 
                         'MEGAN', 'ACHILLES', 'MARK', 'STONE', 'ELEEN', 
                         'BEAR', 'FIRST', 'SHAHNA', 'MIKE', 'BERKELEY', 
                         'VANNA', 'LOSIRA', 'KZIN', 'CHEF', 'AKAAR',
                         'RED', 'COMPTON', 'THREE', 'RAY', 'ORION', 
                         'GENERAL', 'HOLLIDAY', 'GALLOWAY', 'BUILDER',
                         'SOLDIER', 'KEEPER', 'RAYBURN', 'DRUSILLA', 
                         'ALARS', 'RILA', 'DESALLE', 'DRIVER',
                         'SPINELLI', 'MAGEN', 'KURI', 'BROWN', 
                         'GOVERNOR', 'AGMAR', 'STELLA', 'GORGAN', 
                         'BOMA', 'TRADER',  'BARBER', 'DAYSTROM',
                         'THARN', 'LOKAI', 'STAGEHAND', 'ROWE',
                         'NELLIS', 'ALICES', 'APOLLO', 'NATIRA', 
                         'GORGON', 'GIOTTO', 'KELINDA', 'BRAIN',
                         'TULA', 'THEELA',  'DEMOS',  'DON', 'TAMAR',
                         'GARISON', 'DARNELL', 'DIONIYDE', 'STARNES',
                         'A REDSHIRT', 'JOSEPH', 'SAYANA', 'EDITH',
                         'PETRI', 'TAMOON', 'MORLA', 'TRAVERS',
                         'LESLEY',  'TECHNICIANS', 'GUARDIAN',
                         'BETA', 'LOSKENE', 'FLINT','BILLYBELL', 
                         'TELLARITE', 'TORMOLEN', 'MOTHER', 
                         'WATKINS', 'CHARLIE', 'LIPTON', 'LAZARUS', 
                         'NURSE CHAPEL', 'SEPTIMUS', 'NESVIG',
                         'FIRST OFFICER MISTER SPOCK', 'WALSH', 
                         'JACK', 'CHEIR ENGINEER MONTGOMERY SCOTT', 
                         'GILL', 'FELLINI', 'SHRAS', 'ABROM','WESLEY', 
                         'LANDRU', 'SIRAH', 'JAEGER', 'HENGIST', 
                         'BARIS', 'FARRELL', 'KEEL', 'KELOWITZ',
                         'AMBASSADOR SAREK', 'ATOZ', 'THOMPSON',
                         'AN ENGINEER', 'TELLER', 'GEOLOGIST', 
                         'BEM', 'CLAUDIUS', 'DREA', 'SONNY',
                         'ADAM', 'PILOT',  'TIMOTHY',  'KYLE',
                         'THELEV', 'KRYTON', 'MALLORY', 'ALICE', 
                         'ELDER', 'ALDEN',  'KRAKO', 'ANKA',
                         'LETHE', 'PHILANA', 'FREEMAN', 'DAMATO', 
                         'KOS', 'BURKE', 'TEC', 'CREWMAN','BRYCE', 
                         'ALPHA', 'LATIMER', 'FERRIS', 'RAYNA', 
                         'TRELANE', 'GIRL', 'LEILA', 'KAL', 
                         'MULHALL', 'QUEEN', 'GABLER', 'DECIUS', 
                         'STILES', 'MENDEZ', 'RABBIT', 'RUK', 
                         'DARVIN', 'PERSONNEL', 'CLAYTON', 
                         'CHRISTOPHER', 'SAM', 'JIMMY', 'KOL', 
                         'XERIUS', 'NANCY', 'CORIDAN', 'BEHAN', 
                         'JAMIE', 'ORDERLY', 'TONIA', 'ISAK', 
                         'ALEEK', 'NAVIGATOR', 'DOMAR','KRAS', 
                         'FLAVIUS', 'KANG', 'COGLEY',  'WITCH', 
                         'HARRISON', 'KOROB', 'ZETAR', 'JOHNSON',
                         'MAAB', 'JOHN', 'MERIK', 'PRISONER',
                         'TPAU', 'KRELL','RIZZO', 'TREFAYNE', 
                         'TEENAGER', 'KOLOTH', 'TCHAR', 'OHEA', 
                         'TOMMY', 'GREY', 'HEALER', 'LENORE', 
                         'MINER', 'KUKULKAN', 'AYELBORNE', 'MIRI', 
                         'AMANDA', 'AN ALIEN', 'WYATT', 'SERGEANT', 
                         'STEVE', 'SALISH', 'VEDALA', 'TARK', 
                         'OTHERS', 'COLEMAN', 'AN ENTITY', 
                         'HARRY MUDD', 'AN ADMIRAL', 'KARL', 
                         'ANDREA', 'HAMLET', 'TOMAR', 'KAREN', 
                         'DOCTOR LEONARD MCCOY (BONES)',
                         'DAUGHTER','MARLENA', 'BILAR', 'KRODAK', 
                         'JUDGE', 'MENDANT', 'NEPHRO', 'HACOM', 
                         'LUCIEN', 'KELSO', 'LINDSTROM', 'MATSON',
                         'STOCKER', 'KARLA', 'CARETAKER', 'FEMALE', 
                         'CAPTAIN CHRISTOPHER PIKE','CHIEF',
                         'SYLVIA', 'SURAK', 'MAY', 'KOLSHA', 
                         'STONN', 'KORAX', 'LARS', 'SORD',
                         'WU', 'BOY', 'ENEG', 'LUMA', 'MARKEL', 
                         'MIRANDA',  'ANNE',  'ELIAS',  'TPRING', 
                         'GARTH', 'KOMACK', 'MIDRO', 'FISHER', 
                         'LURRY', 'BARSTOW', 'JIM','BOYCE',
                         'A PAINTER', 'TYREE', 'IRINA', 'MORG',
                         'CARLISLE', 'PLASUS',  'HANSON', 
                         'LYSA', 'MAGISTRATE', 'CLAYMARE', 
                         'ANDROIDS', 'COLT', 'ANNOUNCER', 
                         'LEIGHTON', 'TUT', 'MEA', 'ROBERT',
                         'PARMEN', 'MEARS',  'YEOMAN', 'DEPAUL',
                         'KOR', 'AKUTA', 'HERBERT', 'STAVOS',
                         'DOCTOR', 'A HUMAN', 'NOEL', 'RAHDA', 
                         'ZARABETH', 'ADMIRAL ROSS', 'KLINGONS',
                         'HELMSMAN HIKARU SULU', 'VANDERBERG', 
                         'TROGLYTE', 'JONES', 'RODRIGUEZ',
                         'MRESS', 'AMBASSADOR', 'LARA', 'TAL', 
                         'HAINES', 'POLICE', 'CENTURION'],
                  'TNG': ['BLACKWELL', 'SUPERNUMERARIES',
                          'PRIMARY', 'YARI', 'RIXX', 'KLAG',
                          'FAREK', 'MORTA', 'TYLER', 'RIVERS',
                          'CLOUD', 'PAREM', 'MARLA', 'TOG', 
                          'MINUET', 'HUMANOID', 'KLINGON',
                          'CHEIF ENGINEER GEORDI LA FORGE',
                          'TOFF','FREED','TROOPER', 'DTAN',
                          'NVEK', 'JAMESON', 'KORRIS', 'GOWRON', 
                          'POET', 'BATAI', 'MARTA', 'TOL', 
                          'KEIKO OBRIEN', 'PRESSMAN','PIERCE',
                          'ORTA', 'SEAMAN', 'KOSINSKI', 'LEAH', 
                          'BENSEN', 'REGINOD', 'DARA',  'LIAN',
                          'BROWER','LURIN', 'SETAL', 'GUARDS',
                          'TASHA', 'RIVAN', 'SAVAR', 'ORACLE',
                          'JOBRIL', 'RIVA', 'LAURA', 'HALL', 
                          'ANTHWARA', 'WIDEN', 'GREBNEDLOG',
                          'CRATER', 'PRISONERS', 'RIKER/OBERON', 
                          'ROCKED', 'FIRST OFFICER WILLIAM RIKER',
                          'RAGER', 'MAROUK', 'OKONA', 'RALPH', 
                          'MAURIC', 'VICTORIA', 'KROLA', 
                          'JASON', 'EINSTEIN', 'BELLBOY', 
                          'TACTICAL OFFICER', 'HARITATH', 
                          'LINCOLN', 'BLURRY', 'MCKNIGHT', 
                          'INAD', 'MENDON', 'VULCAN', 'MAURICE',
                          'MELIAN',  'HAYNE', 'DESEVE', 'LIVA', 
                          'SHELBY', 'CONOR', 'PALMER', 'SOLOK',
                          'KMPEC', 'LWAXANA', 'KRISTIN', 'KRITE', 
                          'WOMAN', 'LORE', 'BEING', 'LESTRADE', 
                          'LYNCH', 'RASMUSSEN', 'ALBERT', 'KESTRA', 
                          'HAGON', 'ELINE', 'BEN', 'SCHOLARARTIST', 
                          'PERRIN', 'JENNA', 'LAKANTA', 'YAREENA', 
                          'CHILTON', 'SPIKE', 'GRAVES', 'NURSE',
                          'BOK', 'BAJORAN ENSIGN RO LAREN', 
                          'CHILDREN', 'CASTILLO', 'TPEL',
                          'KOROTH', 'COLONEL', 'GOSHEVEN', 
                          'OJI', 'BAILEY', 'ROMULAN', 'KAHLESS', 
                          'TARSES', 'CREWWOMAN', 'ERIC', 
                          'ISABELLA', 'GOSS', 'SONGI', 'IAN',
                          'WILSON', 'ROMAS', 'SERGEY', 'ERKO',
                          'EGO', 'LELAND', 'MERCHANT', 'ARIEL', 
                          'DOCTOR BEVERLY CRUSHER','COMPUTER',
                          'ANNIE', 'CARLOS', 'ALEXANDER', 'OLIANA', 
                          'HELMSMAN', 'VEKMA', 'PEEPLES', 'CLARA',
                          'CHRISTY', 'CHEIF ENGINEER MILES OBRIEN',
                          'CONDUCTOR', 'DURAS', 'MENDOZA',  'VORIN', 
                          'JEFFREY', 'JORET', 'PARDEK', 'PARIS',
                          'KARGAN', 'HANNAH', 'MORDOC', 'MENDAK',
                          'TEACHER', 'MIRASTA', 'CADET','MAJOR', 
                          'CREWMEMBERS', 'FARALLON', 'ROMULAN2',
                          'WES', 'TAIBAK', 'RENE', 'NOOR', 'DARO',
                          'SATLER', 'HALFOLD', 'APRIL', 'KAMINER', 
                          'PENNY', 'MACDOUGAL', 'SECURITY', 
                          'DANILO', 'KTEMOC', 'GOVAL', 'KAPLAN', 
                          'ALEXANA', 'SAKKATH', 'SECRETARY', 
                          'RAL', 'DOLAK', 'PROBE', 'YRIDIAN', 
                          'CAPTAIN MONTGOMERY SCOTT (SCOTTY)',
                          'POLICEMAN', 'HAJAR', 'TECHNICIAN', 
                          'KALITA', 'BATES', 'DAVIES', 'KOLRAMI', 
                          'JIKO', 'KARNAS', 'HELM OFFICER','JUNGLE', 
                          'TARIS', 'ROGA', 'DEVOR', 'SUPERVISOR', 
                          'SIRANNA', 'PRAK', 'CARA', 'SIROL', 
                          'TABLE', 'DUANA', 'ROS', 'CREDITS', 
                          'KEVIN', 'WHALEN', 'MEN', 'PANS', 
                          'PAKLEDS','THANIK', 'GARVIN', 'MISTRESS', 
                          'HEAD', 'ZORN', 'MARTIN', 'HARO', 'MALL',
                          'TRAIN', 'COUNTESS', 'OVERSEER', 'TAU', 
                          'TJON', 'KAREEL', 'LIEUTENANT', 'HEDRIL', 
                          'WALLACE', 'CHIMES', 'SOONG', 'BEATA', 
                          'SANDERS', 'MCDOWELL', 'GUARD', 'KAZAGO',
                          'SINGH', 'ARGYLE', 'ANDREW', 'BRACTOR',
                          'DOT', 'NILREM','MANDARIN', 'BIJIK', 
                          'GARRETT', 'LARSON', 'MATURIN', 'CREW',
                          'MORGAN', 'OFFICER', 'ETHAN', 'EARHART', 
                          'MINISTERS', 'GIUSTI', 'QUINN', 'INSECT',
                          'MALENCON', 'RABAL', 'CARDASSIAN', 
                          'PATTERSON', 'JADAR', 'JONO', 'SATELK', 
                          'ENSIGN', 'TECH', 'DATHON', 'CORAK',
                          'MAN', 'GRANDFATHER', 'SEROVA', 'FERENGI',
                          'GINGER', 'CLANCEY', 'TORAK', 'TIMICIN',
                          'HILDEBRANT', 'LKOR', 'MARK', 
                          'STONE', 'BROOKS', 'BHAVANI',
                          'ANOTHER', 'GRACE', 'WILLIAMS',
                          'SANTOS', 'VENDOR', 'PARKLAND',
                          'GRAY', 'MIKE', 'BENZAN', 'GUARD2',
                          'TAYNA', 'LEMEC', 'CONNAUGHT', 
                          'CALLOWAY', 'MUROC', 'BAEL', 
                          'HALI', 'ODAN', 'ROBOT', 
                          'KANE', 'SHIPLEY', 'MADDOX', 'FRAY', 
                          'TPAN', 'BOOTHBY', 'CHAPMAN', 
                          'DEBIN', 'QOL', 'KRIOS', 'CAPTAIN',
                          'CROUPIER', 'DEVINONI', 'RISHON', 
                          'THREE', 'SUDDENLY', 'RAY', 'KENNELLY', 
                          'JUGGLER', 'CHILD', 'KAREEN',
                          'GORDON', 'WRENN', 'GENERAL', 'SOLDIER', 
                          'GABRIELLE', 'FELTON', 'LEADER', 'NURIA',
                          'KEEVE', 'JEV', 'CAMPIO', 'ELI', 'COREY',
                          'ANYA', 'HUNTER', 'MERIBOR', 'JAROK', 
                          'NAKAMURA', 'KEEPER', 'SCIENTIST', 
                          'HARRY', 'TRANSLATOR', 'AARON',
                          'HER', 'FIGURE', 'LOCUTUS', 'KURAK', 
                          'LORIN', 'SOLIS', 'GOVERNOR', 'MAQUES',
                          'TOMOLAK', 'LEDA', 'DNA', 'KENTOR', 
                          'LOCARNO', 'KELLY', 'AIDE', 'NARA', 
                          'BASHIR', 'BRENNA', 'GRAND', 'SENATOR',
                          'SARJENKA','BARBER', 'ENDAR','FRANCINE', 
                          'ALRIK', 'TRADER', 'TOPS', 'SHREK',
                          'JARTH', 'DAYSTROM', 'SOREN', 'RANGES', 
                          'ESOQQ', 'CUSTOMER', 'TEBOK', 'MACIAS', 
                          'MALE', 'JEAN', 'VANESSA', 'CROSIS', 
                          'RUSSELL', 'OMAG', 'MACET', 'KMTAR',
                          'CREWMEMBER', 'BNAR', 'BELL', 'APGAR',
                          'BRAIN', 'TRYLA', 'PATAHK', 'FAJO',
                          'MENDROSSEN',  'NECHAYEV','GARIN', 'REX', 
                          'ALLENBY', 'TAAR', 'PATIENT', 'LANGOR',
                          'TOMALAK', 'SUNAD', 'LUISA', 'BAH',
                          'BEGGAR', 'YUTA', 'TOKATH', 'TECHNICIANS',
                          'JESSICA', 'SOLDIERS', 'MONTGOMERY SCOTT',
                          'MOTHER', 'SEMI', 'LAL', 'REDBLOCK', 'NERAL',
                          'ANNA', 'OKUDAGRAM', 'CAPTAIN JEAN LUC PICARD', 
                          'COUNSELOR DEANNA TROI', 'BARTEL','GIRAL', 
                          'TROOPS', 'MORIARTY', 'CLARE', 'HEDRICK', 
                          'PAUL', 'SHOPKEEPER', 'ISAAC NEWTON', 
                          'STAIN', 'WAITER', 'SUTTER',  'BETA',
                          'ENGINEERING OFFICER','NUDAQ',  'THOLL', 
                          'MCNARY', 'TAM', 'AMBASSADOR SPOCK', 'JACK', 
                          'DEALER', 'GILL', 'PEERS', 'TALL', 'HESTER',
                          'GIBSON', 'MOVAR', 'VAL', 'AMARIE', 'EMILA', 
                          'DISEMBODIED VOICE', 'TORIN', 'BARAN',
                          'ROMULAN 1', 'FREUD', 'KAYRON', 'ENGINEER',
                          'GALEN', 'SITO', 'WARREN', 'VI', 'MADRED',  
                          'JARED', 'HAYES','YANAR', 'LIZARD',
                          'OFFICIAL', 'KVADA', 'SONNY', 'ASSISTANT', 
                          'DISAPPEARS', 'KTAL', 'ALEXANDRA', 
                          'KEEL', 'VISOR', 'PILOT', 'LEFLER', 
                          'HOMN', 'ARRIDOR', 'STUDENTS', 'VOLNOTH',
                          'KURN', 'MALLORY', 'KONMEL',  'TAITT', 
                          'DOORMAN', 'STEVEN', 'BATESON', 
                          'SPECTRE','AMBASSADOR SAREK', 'DURKEN',
                          'JULIANA', 'MARISSA', 'GRAHAM', 
                          'COMMANDER', 'PRAN', 'ENGINEERS', 
                          'NAUSICAAN', 'SHIMODA', 'LAVELLE',
                          'SURVIVOR', 'GORTA', 'HAH', 'PHILLIPA',
                          'MOSELEY', 'GUL', 'CREWMEN', 'LIKO', 
                          'SOVAK', 'MOTHERS', 'BURKE', 'VEKOR', 
                          'CREWMAN','PRIME','TALLERA', 'NIKOLAI', 
                          'BEREL', 'KYLE', 'SALVAGE CAPTAIN',
                          'TACTICIAN', 'LIEUTENANT WORF ROZHENKO', 
                          'REYGA', 'TIMOTHY', 'ADAM','ALPHA',
                          'INDIGINEOUS PERSON', 'TEMAREK',
                          'HAWKINS','DOCTOR KATHERINE PULASKI',
                          'JOVAL', 'BOCHRA', 'AJUR', 'VAGH', 
                          'LURSA', 'MOLLY', 'DRAKE', 'RINA',
                          'FINN', 'NARIK', 'KAMALA', 'TRENT',
                          'ANDROID SECOND OFFICER DATA SOONG', 
                          'MENDEZ', 'RABBIT', 'ISHARA', 'SELA', 
                          'NAYROK', 'CIVILIAN',  'SAM', 'ORTON',
                          'BROSSMER', 'TAGGERT', 'KEHLEYR', 
                          'PERSONNEL', 'STUBBS', 'CHEKOTE', 
                          'AQUIEL','HITMAN', 'CHANDRA', 'KIM', 
                          'CHRISTOPHER', 'POMET', 'MANHEIM', 
                          'LIATOR', 'KOL', 'HASKELL', 'ARDRA', 
                          'VAREL', 'GAINES', 'LIN', 'QUINTEROS',
                          'KATIK', 'DERN', 'ROBINSON', 'KATIE', 
                          'FENTO', 'JANEWAY', 'STABLE', 'MOTT', 
                          'MORDOCK', 'ARIANA', 'BYLETH', 'KING', 
                          'UZANI', 'OWEN', 'OGAWA', 'ADMIRAL JELLICO', 
                          'DOCTOR BEVERLY CRUSHER', 'FATHER', 'NOISE', 
                          'EMIL', 'BARRON', 'SONYA', 'NEIL', 'SOTTO', 
                          'JOHN', 'ALKAR', 'KIROS',  'JEREMY', 'ARMUS',
                          'TRAVELLER', 'PRISONER', 'DUFFY', 'MACDUFF', 
                          'KRAG', 'FELINE', 'CHANCELLOR', 'RHODES',
                          'JESSEL', 'TOMMY', 'BORG',
                          'PAH', 'GILLESPIE', 'SHELIAK', 'TRAVELER',
                          'ICO', 'DOKACHIN', 'TARMIN', 'HELENA', 
                          'HEALER', 'BARCLAY', 'BRIAM', 'PRYTT', 
                          'EDOUARD', 'WYATT', 'DOBARA', 'TORAL', 
                          'MINER', 'SALIA', 'ROBIN', 'AMANDA',
                          'ALIEN', 'KAMIN', 'GLEASON', 'MIKEY', 
                          'COMMANDANT', 'NIBOR', 'OTHERS', 'ACCOLAN', 
                          'ENTITY', 'JARADAN', 'CLEMENS', 'LEYOR',
                          'BAJORAN', 'ETANA', 'PHYSICIAN', 
                          'KUSHELL', 'QUINT', 'WESLEY CRUSHER', 
                          'RAMSEY', 'PULL', 'BARNABY',
                          'LETEK', 'KATERAS', 'BERIK', 'LANA',
                          'REGULATOR', 'MOIRA', 'LEKA', 'GUINAN', 
                          'JUDGE', 'MANUA', 'WORKMEN', 'KELL',
                          'LUTAN', 'ADMIRAL NECHEYEV', 'ADMIRAL', 
                          'SEX WORKER','WILLIE', 'HUGH',
                          'PRICE', 'JAKE',  'KELSO', 'NIGHT', 
                          'BORATUS', 'SUPERNUMERARY', 'TOQ',
                          'RICE', 'PHASER', 'LARG', 'SABIN', 'NELLA', 
                          'ENGINEER GEORDI LAFORGE', 'PORTAL',
                          'YRANAC', 'HANSON', 'NAGILUM', 'DIRGO', 
                          'RUFFIAN', 'FLORA', 'MANDL', 'TORETH',
                          'HOBSON',  'FEMALE', 'MANDEL',
                          'EDOLORD', 'HUTCHINSON', 'SARIEL',
                          'BTARDAT', 'DIVOK', 'OPERATIVE',
                          'SATOK', 'SURGEON', 'HAGAN', 
                          'CUSTODIAN', 'ANNETTE', 'KAHLEST', 
                          'DEPUTY', 'HEAR', 'CLANG', 'GIA', 
                          'CHIEF MILES OBRIEN', 'BOY', 'BUCK', 
                          'LOQUEL', 'VARRIA', 'RONIN', 'KELSEY', 
                          'MIRANDA', 'RUBY', 'FOREMAN', 'LOUIS',
                          'HICKMAN', 'JDAN', 'CHANG', 
                          'ALYSSA', 'LOGAN', 'VASH', 'MOT',
                          'ADMIRAL JAMES TIBIRIUS KIRK (JIM)',
                          'MARIE', 'REMMICK', 'PAVLIK', 'REM', 
                          'PRO', 'BETOR DURAS', 'SERVANT', 
                          'BENBECK', 'SOBI', 'WAKASA', 'MORAG',
                          'ALANS', 'MICHAEL', 'TALUR',
                          'ANDROIDS', 'MARKHAM', 'GAMBLER',
                          'FEDERATION PRESIDENT',  'GRANGER',
                          'MIROK', 'BIRTA', 'HENRY', 'ROBERT', 
                          'TAVA', 'PGO', 'DAVIS', 'HERBERT',
                          'SUSANNA', 'MAYLOR', 'ARDRIAN', 
                          'CHORGAN', 'DOCTOR', 'HUMAN', 'MOLOR', 
                          'RASHELLA', 'WARRIORADONIS', 
                          'CPK', 'KORAL', 'SLADE', 'TAURIK', 
                          'SKORAN', 'ANNE', 'KLINGONS', 
                          'DOG', 'KNERA', 'BADAR',  'MAXWELL', 
                          'TELLE', 'RADUE', 'TAH', 'RONARA',
                          'BRULL', 'POLICE', 'AMBASSADOR', 
                          'ATTENDANT', 'CENTURION', 'ROMULAN'],
                  'DS9': ['SUPERNUMERARIES', 'PRIMARY', 'BRATHAW', 
                          'ARISSA', 'HUMANOID', 'KLINGON', 
                          'WORF/ALIEN', 'KEIKO OBRIEN',
                          'CASSANDRA', 'CJ57436',  'TRAVIS',
                          'TIMOR', 'ZEPHRAM COCHRANE', 
                          'MULKAHEY', 'PROKA', 'LURIN', 'LUPAZA',
                          'KALANDRA', 'CHTARGH', 'GRIMP',
                          'LISA', 'YEDRIN', 'KNIGHT', 'FROOL',
                          'ONAYA', 'KARA', 'SHEL',  'FENNA',
                          'MIDWIFE', 'WEBB', 'RUSOT', 'ELIZABETH',
                          'GUARDS', 'TRAIDY', 'ROM', 'HALL', 
                          'PRISONERS', 'CHRIS', 'CRATER',
                          'ROCKED', 'THOMAS RIKER', 'DOREK',
                          'GENERAL MARTOK', 'JABARA', 'LI', 
                          'BEK', 'BASS', 'VIC', 'TARKALEAN',
                          'FREED', 'ARAKTARAL', 'PATRON', 
                          'GOWRON', 'TIRON', 'TACTICAL', 'DRAIN',
                          'KOH', 'BOKAR', 'AMATIGAN', 'HADAR',
                          'RIVERS', 'MORA', 'VULCAN', 'GANTT', 
                          'KORNAN', 'SHELBY', 'TOSK', 'SIANA', 
                          'LAMATUKAN', 'VORTA', 'JIMENEZ', 'SOLOK',
                          'NORI', 'GRAL', 'SAKONNA', 'LEETA/EMONY',
                          'LWAXANA TROI', 'BOLIAN', 'ALBERT', 
                          'ISHKA (MOOGIE)', 'BASSO', 'BORUM', 
                          'RASMUSSEN', 'WOBAN', 'KESTRA', 'SARAH', 
                          'BEN', 'COMPANION', 'VARIS', 'JEM HADAR', 
                          'TABAN', 'TEKOA', 'NOG', 'KELLIN', 
                          'MAJOR KIRA NERYS', 'ENTEK',  'COLONEL', 
                          'ADMINISTRATOR', 'GRAVES', 'NURSE', 
                          'KIRA/PROPHET', 'CHILDREN', 'FALOW', 
                          'WHATLEY', 'RAMIREZ', 'STOLEN', 'KOLANA',
                          'NINERS', 'PIERSALL', 'SKIM', 'LEE', 
                          'HAZAR', 'JADZIA DAX','MERCHANT', 
                          'EBLAN', 'EMI', 'COLYUS', 'SUB COMMANDER',
                          'YELGRUN', 'SURMAK', 'GOSS', 'LEYTON',
                          'DEVICE', 'BOONE', 'ROMULAN', 'YETO', 
                          'LENARA', 'VORNAR', 'OKAY', 'MARRITZA', 
                          'DEWILDETV', 'ENABRAN TAIN', 'SECRETARY', 
                          'ALEXANDER ROZHENKO', 'VARANI', 
                          'BROCA', 'TUMAK', 'COUNTMAN', 'DURAS',
                          'CHEIF ENGINEER MILES EDWARD OBRIEN', 
                          'BENYAN', 'ODO/CURZON', 'PARIS',  
                          'COMPUTER', 'KAHLESS', 'ONARA', 'JONAS', 
                          'IBUDAN', 'TEACHER', 'FAREN', 'CICCI', 
                          'CREWMEMBERS', 'KEEVAN', 'KEOGH', 
                          'DECKER', 'APRIL', 'BRUNT', 'SECURITY',
                          'CADET', 'HOYA', 'MADAM',  'BEJAL',
                          'FULLERTON', 'ENERGY', 'PADDS', 'HANEEK',
                          'KAINON', 'ZLANGCO', 'CAL', 'KOVAT', 
                          'HOVATH', 'SARINA', 'CRODEN', 'HELMSMAN', 
                          'GANGES', 'SAMUELS', 'LEWIS ZIMMERMAN',
                          'POLICEMAN', 'KALITA', 'TECHNICIAN', 
                          'ZEEMO', 'VIN', 'ISHAN', 'MEN', 'COS',
                          'TOMANTORAX', 'REMATAKLAN','SHAPESHIFTER',
                          'ARGRATHI', 'BENTEEN',  'SILARAN',
                          'KUDAKETAN', 'PROBE', 'YRIDIAN', 'TABLE', 
                          'KORENA', 'KHAN', 'NIDELL', 'ROS', 
                          'JUNGLE', 'TOH', 'LUCSLY', 'NOGGRA', 
                          'GELNON', 'RETAYA', 'TREVEAN', 'MISTRESS', 
                          'DECURTIS', 'BASHIR/TORIAS', 'TAVANA', 
                          'OVERSEER', 'GUARD', 'SINGH', 'STEVENS',
                          'FARRAKK', 'SELTIN', 'ALSIA', 'JOMAT',
                          'LIEUTENANT', 'GABRIEL', 'SANDERS', 
                          'MINISTERS', 'IXTANARAX', 
                          'MIRROR KIRA (INTENDANT)', 'MIRROR BASHIR', 
                          'MIRROR BRUNT', 'MIRROR EZRI', 'MIRROR QUARK', 
                          'MIRROR NOG', 'MIRROR ROM', 'MIRROR GARAK', 
                          'MIRROR ODO', 'MIRROR GUL DUKAT', 
                          'YOH', 'CHESTER', 'DAX', 'ALTOVAR', 'SMILEY', 
                          'BANDEE', 'OFFICER', 'MULLIBOK', 
                          'CREW', 'FARRIS', 'TEMOZUMA', 'COLLINS', 
                          'QUARK/AUDRID', 'ENSIGN', 'TECH', 
                          'BRILGAR', 'SOLBOR', 'OPAKA', 'ETYSHRA', 
                          'CARDASSIAN', 'HAGATH','MIRROR DAMAR',
                          'MIRROR BENJAMIN SISKO',  'GRACE',
                          'MAN', 'GRANDFATHER', 'PATRICK', 'TAI', 
                          'FERENGI', 'HAIN', 'GINGER', 'TELI', 'WANNA',
                          'MARK', 'ANOTHER', 'HICKAM', 
                          'PKAR', 'HALB', 'REBECCA', 'MAREEL',
                          'ILARIO', 'NYDROM', 'NAHSK', 'AKOREM', 
                          'MIKE', 'MELORA', 'ORNITHAR', 'BENNY', 
                          'LOS', 'SHEPARD', 'MIKA', 'BELAR', 'LEANNE',
                          'BODAN', 'SHARAT', 'KROLE', 'CHEF',
                          'MELISSA', 'TANDRO', 'CROUPIER', 
                          'LARKIN', 'RAY', 'FELTON', 'HUNTER',
                          'HUDSON', 'RIONOJ', 'JAKE/PAH', 'CHILD',
                          'KARINA', 'CHANGELING', 'ORION', 
                          'LEADER', 'GENERAL', 'NORVO', 'CAPTAIN',
                          'ASHROCK', 'RURIGAN', 'GRADY', 'SOLDIER', 
                          'INGLATU', 'ATUL', 'YARKA', 'DEJAR',
                          'DRIVER', 'VALERIAN', 'SCIENTIST', 'TUMEK',
                          'ARJIN', 'TAYA', 'PABST', 
                          'KOBB', 'LOCUTUS', 'SYNON', 'DKAR', 
                          'KORINAS', 'BROWN', 'GOVERNOR', 
                          'TKAR', 'DREX', 'AMARO', 'JAKIN', 
                          'DOCTOR JULIAN BASHIR', 'GRAND NAGUS ZEK', 
                          'GORANAGAR', 'SENATOR', 'NGAREN',
                          'HILLIARD', 'HOGUE', 'KAGAN', 
                          'KRIM', 'TRUL', 'BROTA', 'WEYOUN', 
                          'INTENDANT', 'MORKA', 'PRAETOR',
                          'LUARAN', 'INORA', 'KUBUS', 'CREWMEMBER', 
                          'NEELA', 'RUSSELL', 'FRAY',
                          'LASARAN', 'GABRIEL BELL', 'DAROK', 
                          'TAHNA', 'PECHETTI', 'PREN', 'AL', 'STEPHAN', 
                          'MARDAH', 'KILANA', 'PETRI', 
                          'JENNIFER SISKO',  'GUARDIAN',
                          'RAZKA', 'ALL', 'MIRROR JENNIFER', 
                          'POPS', 'PRIMMIN', 'JOSEPH', 'BEGGAR',
                          'TECHNICIANS', 'FALA', 'SARISH',
                          'ODO', 'KRIT', 'ZEFNO', 'SHOPKEEPER', 
                          'JESSICA', 'SOLDIERS', 'MERU', 
                          'OKUDAGRAM', 'NERAL', 'PICARD', 'TROOPS',
                          'CHARLIE', 'ENINA', 'MAKBAR', 'SPECTRE',
                          'SIRELLA', 'WAITER', 'NATIMA', 'ENGINEERS', 
                          'GAILA', 'OFFICIAL', 'RENORA', 'ELDER', 
                          'RYAN', 'SEPTIMUS', 'FRANKIE','KURN', 
                          'JACK',  'PRESTON',  'ARI', 'ASSISTANT',
                          'BAREIL', 'DURG', 'MESOCLAN', 'ORTAKIN',
                          'SIRAH', 'DISEMBODIED VOICE', 'DARK',
                          'ENGINEER', 'BRAT', 'JORANOS', 'EZRI DAX',
                          'THOMPSON', 'STATIC', 'LETANTALIEN', 
                          'DEYOS', 'OMETIKLAN', 'MONK', 'DISAPPEARS', 
                          'STOLZOFF', 'LESKIT', 'TRILL', 'JANEL',
                          'PILOT', 'HELER', 'ERIS', 'ALBINO', 'BOQTA', 
                          'RUWON', 'PREACHER', 'ALICE', 'STUDENTS',
                          'PADAR', 'USS', 'BOHEEKA', 'JULIUS', 
                          'THOPOK', 'BARKEEP', 'RAIMUS', 'ZOLAN',
                          'AMSHA', 'SORM', 'WYKOFF', 'CHADWICK', 
                          'COMMANDER', 'PRAN', 'HIM', 'NAUSICAAN',
                          'GHEMOR','MOTHERS', 'ALPHA', 'VINOD', 
                          'GUL', 'HURAGA', 'CREWMEN', 'ANARA', 
                          'RUMPELSTILTSKIN', 'BURKE', 'KTEMANG',
                          'CREWMAN', 'SALVAGE', 'ARBITRATOR', 'KAY', 
                          'COMMANDER WORF ROZHENKO', 'CHPOK', 
                          'HAWKINS', 'GARAK', 'HOLO', 'LURSA DURAS', 
                          'ARANDIS', 'MOLLY', 'GIRL', 'MPELLA', 
                          'DRONE', 'MOOGIE', 'CIVILIAN', 'SESKAL',
                          'DARVIN', 'PERSONNEL', 'BORATH', 'ROY', 
                          'WATTERS', 'PALLRA', 'PARN', 'LUVSITT', 
                          'MUNIZ', 'NATHAN', 'YASSIM', 'SAHGI', 
                          'YPORA', 'NEELEY', 'ULANI', 'BERNARDO', 
                          'JIMMY', 'KOVAL', 'KAI WINN', 'TURREL', 
                          'MARTUS', 'FREIGHTER CAPTAIN KASIDY YATES',
                          'NAVA', 'RENHOL', 'CHANDRA', 'CHEKOTE', 
                          'TLARA', 'CAPTAIN BENJAMIN SISKO', 'A WAITER', 
                          'LECK', 'SHAKAAR', 'KANG', 'A PRISONER',
                          'TRAJOK', 'SLOAN', 'LANG', 'EMIL', 
                          'GILORA', 'TOLAR', 'MOH', 'VELAL', 'KOLOTH', 
                          'FLIGHT', 'PEL', 'RISKA', 'SPARKS', 'KING', 
                          'CHANDLER', 'TEENAGER', 'VARGAS', 'AN ADMIRAL', 
                          'LEGATE', 'BROIK', 'SENATOR CRETAK', 'JASAD', 
                          'TRAZKO', 'OPENS', 'BARTENDER','LAUREN', 'JAH', 
                          'LENARIS', 'VANTIKA', 'CHANCELLOR GOWRON',
                          'GINT', 'BORG', 'SYVAR', 'PAH WRAITH', 
                          'KAYBOK', 'SLOTH', 'ENTITY', 'PHYSICIAN', 
                          'REGINALD BARCLAY', 'DULMUR', 'JARO',
                          'ALIEN', 'COUTU', 'OTHERS', 'TORAL',
                          'BAJORAN', 'FLASH', 'EDDINGTON', 'JUDGE', 
                          'MILA',  'TORAN', 'QUARK',  'COPS', 
                          'MELANIE', 'FLITH', 'GARRISON', 'NIGHT',
                          'LOVOK', 'WATLEY', 'TALAKTALAN', 'BILBY',
                          'FALL', 'DOCTOR LEONARD MCCOY (BONES)',
                          'HANOK', 'EKORIA', 'REGENT', 'CARSON',
                          'VERAD', 'LEETA', 'TELOK', 'SEYETIK',
                          'EKOOR', 'RUGAL', 'WORKMEN', 'KELL', 
                          'NILVA', 'ADMIRAL NECHEYEV', 'ROANA',
                          'WELDON', 'JAKE', 'PRICE', 'WILLIE',
                          'LOUIS', 'YARETH', 'PORTA', 'KAI OPAKA',
                          'SUPERNUMERARY', 'KAREN', 'DAMAR',
                          'AMAROS', 'KRAX', 'IDANIAN', 'KIRBY',
                          'TODDMAN', 'FUCHIDA', 'GUL DUKAT', 
                          'OPERATIVE', 'CASSIE',  'DARLENE', 
                          'BRIN', 'MAY', 'SURGEON', 'BALL',
                          'ROSS/ALIEN', 'DANNY', 'EECHAR',
                          'CONTROL', 'MIRANDA', 'TILIKIA', 
                          'KORAX', 'DEPUTY', 'KOLOS', 'CLANG',
                          'CHIEF', 'LOLA', 'ILIANA',  'KAJADA', 
                          'BOY', 'DERAL', 'LUMA', 'BUCK',
                          'ATOA', 'YANAS', 'ALIXUS', 'REKELEN',
                          'BUSINESSMAN', 'DAD', 'KIRALELA',
                          'SISKO/JORAN', 'FAH', 'JIM', 'GRILKA', 
                          'TYREE', 'ZIYAL', 'BETOR', 'SERVANT',
                          'THRAX', 'GIGER', 'TAMAL', 'LIGHTS',
                          'ZYREE',  'VASH', 'MARTOK/ALIEN', 
                          'LARELL', 'MICHAEL', 'GREEN', 'BOYCE', 
                          'MAGISTRATE', 'RICHARD', 'DGHOR',
                          'VREENAK', 'PRESIDENT', 'KESHA', 
                          'JEYAL',  'FUREL', 'BENNETT', 'ASOTH', 
                          'GAMBLER', 'YOLAD', 'MORN', 'KOR',
                          'HERBERT', 'BATTER', 'LIMARAON',
                          'DOCTOR', 'JARESH', 'HUMAN', 'REESE',
                          'GAI', 'ROSS', 'KLINGONS', 'COOK', 
                          'IKATIKA', 'JONES', 'JORAN', 'POLICE',
                          'VIRAKKARA', 'TAH','AMBASSADOR', 'HENRY', 
                          'ATTENDANT', 'EPRAN', 'JAHEEL'],
                  'VOY': ['KIR', 'TRAJIS', 'KAFAR','MAGGIE', 
                        'HUMANOID', 'OVERLOOKER', 'KLINGON',
                        'DAELEN', 'COCHRANE', 'LAURA', 'MIRELL', 
                        'GENTRY', 'DEVRO', 'PENK', 'BAXTER', 
                        'EMERGENCY COMMAND HOLOGRAM', 'JASON', 
                        'SKLAR', 'KAZON', 'JAMESON', 'DIVA',
                        'LISHAN', 'MARLA', 'HOGAN', 'LATIKA',
                        'TEBBIS', 'AI', 'NAMON', 'WOMAN', 
                        'LONZAK', 'QRET', 'SVEN', 'ELIZABETH',
                        'GUARDS', 'FITZGERALD', 'MARTIS', 'RULAT', 
                        'TRICORDER', 'PRISONERS', 'YOST', 'RAZIK', 
                        'WILLIAM RIKER', 'ROLLINS', 'JOE', 'AUGRIS',
                        'ANDREWS', 'KLEG', 'TARKALEAN', 'FREED',
                        'PATRON', 'TACTICAL', 'JARET',  'DALETH',
                        'QATAI', 'WEAPON', 'KOLOPAK', 'ASSAN',
                        'NICOLETTI','MABUS', 'NORI','SABRINA',
                        'CHORUS', 'VOJE', 'LESSING','EVANSVILLE',
                        'IRENE', 'MALIA', 'MARAYNA', 'ZIO',
                        'VULCAN', 'MORIN', 'LI', 'DONIK', 
                        'TRINA', 'ZAREH', 'JENKINS', 'DAGGIN', 
                        'BEING', 'RAHMIN', 'BOLIAN', 'ALLOCATOR',
                        'KRADIN','ANNIKA HANSEN', 'KELLIN', 
                        'GEDRIN',  'KOVIN', 'CAYLEM', 'RILEY',
                        'MARSEILLES', 'TORAT', 'COMPANION',
                        'ADMINISTRATOR', 'NURSE', 'NOGAMI',
                        'FREYA', 'FENNIM', 'GILMORE', 'CARLOS', 
                        'EMH1', 'CAREY', 'FRESH', 'TIERAN', 
                        'HUSBAND', 'PIRI', 'STETH', 'CHELL', 
                        'CREWWOMAN', 'KIPP', 'INDIGINEOUS LEADER',
                        'NUNK', 'EUDANA', 'SCHARN', 'ONELLA',
                        'TRICE', 'JOR', 'CURNETH',  'SWINN',
                        'LOQUAR', 'MARY', 'ROMULAN', 'ADAR',
                        'MERCHANT', 'JEFFREY',  'YEK',  'BARD', 
                        'HELMSMAN', 'TPEL', 'RAIN', 'VEN',
                        'LOKEN', 'SANDRINE', 'ASTRONOMER',
                        'TOM PARIS', 'TEMPLETON', 'COMPUTER',
                        'KAHLESS', 'SILVER BLOOD PARIS', 'LEUCON',
                        'FIRST OFFICER TUVOK', 'JONAS', 'LIBBY',
                        'GEGIS', 'ALZEN', 'TOMIN', 'AUTARCH', 
                        'RISLAN', 'TAKAR', 'CADET', 'GUILL',
                        'OXILON',  'RAVOC', 'KORATH', 'ALICIA',
                        'PROBE', 'JERO',  'ENERGY', 'SECRETARY',
                        'OBRIST', 'PEMH', 'BURLEIGH', 'KAPLAN',
                        'IDEN', 'SECURITY', 'LYRIS', 'VINKA',
                        'MULCHAEY', 'MALIN', 'YUN', 'JABIN',
                        'WIXIBAN', 'ELIANN', 'UMALI', 'POLICEMAN',
                        'TECHNICIAN', 'COLONEL', 'CHILDREN', 
                        'VIHAAR', 'CLOWN', 'JARETH', 'SHAW', 
                        'HENDRICKS', 'ISHAN', 'SHARON', 
                        'LOKIRRIM', 'SUPERVISOR', 'REBI', 
                        'LEWIS ZIMMERMAN', 'AZAN', 'JETAL',
                        'SEAMUS', 'YEGGIE', 'TALEEN', 'FERENGI',
                        'TABLE', 'SEK', 'BOTHAN', 'HIROGEN',
                        'BOSAAL', 'MEN', 'COS', 'ZAR', 'HEAD',
                        'VEER', 'TAU', 'LIDELL', 'KRAY', 'MARI',
                        'LIEUTENANT', 'HROTHGAR', 'FRANE',
                        'MITCHELL', 'OFFICER', 'ONQUANII',
                        'RIGA', 'GUARD', 'ANDREW', 'TAYMON', 
                        'MEZOTI', 'VARN', 'OZAAL', 'VEL',
                        'VIDIIAN',  'COLLINS',  'BROOKS',
                        'DREMK', 'NERIA', 'RETTICK', 'SUSPIRIA', 
                        'QUARREN', 'CREW', 'VARETH', 'GRACE', 
                        'GRANDFATHER', 'EMH MARK TWO', 'KEJAL',
                        'HARREN', 'PENNO', 'EARHART', 'TREVIS', 
                        'INSECT', 'SULAN', 'ENSIGN', 'KES',
                        'QUINN', 'PATTERSON', 'RAND', 'GENERAL',
                        'ERIN', 'MOSET', 'CARDASSIAN', 'ORUM',
                        'NAOMI WILDMAN', 'MEGAN', 'ADIN',
                        'STONE', 'AVEK', 'TUREI', 'ANNORAX',
                        'ICHEB', 'CULHANE', 'DAVE', 'ABADDON',
                        'MIKE', 'DUNBAR', 'CHILD', 'MEDIC',
                        'LIEUTENANT ENGINEER BELANNA TORRES',
                        'LAW', 'BANETH', 'FRED', 'CHARLENE', 
                        'DAMMAR', 'STARLING', 'BOOTHBY', 'YEDIQ',
                        'CHAPMAN', 'NAKAHN', 'TINCOO', 'RANEK',
                        'BENARAN', 'MONSTER', 'BEATRICE',
                        'SUDDENLY', 'THREE', 'TELEK', 'NIMIRA', 
                        'MOKLOR', 'CHELLICK', 'SWITCH', 'LEADER',
                        'FIRST OFFICER CHAKOTAY', 'DEJAREN',  
                        'ALIXIA', 'SOLDIER', 'CAPTAIN KATHERINE JANEWAY',
                        'KELIS', 'GERRON', 'HUNTER','NOSS', 'TRANSLATOR', 
                        'CULLUH', 'SCIENTIST', 'ENSIGN HARRY KIM', 
                        'TAYA', 'WEISS', 'SUTOK', 'TERSA', 
                        'TUVIX', 'LOCUTUS','KELLY', 'CHREGA',
                        'HALUK', 'ROBOT', 'PTERA', 'KARYA', 
                        'AZEN', 'GRAND', 'NAR', 'DEAN', 'TRESSA',
                        'DURST', 'CLOSE', 'TANIS',  'TESSA', 
                        'OTRIN', 'HENLEY', 'DAYSTROM', 'DAROD',
                        'GEGEN',  'LANNA',  'PTEDRAN', 'VORIK',
                        'TOSCAT', 'JEAN', 'BULLOCK', 'MAKULL',
                        'CREWMEMBER', 'ELANI', 'JETREL', 'BRAIN',
                        'SURAT', 'TASH', 'YIVEL', 'GERAL', 'TGRETH', 
                        'PATIENT', 'CHAOTICA', 'TEDRAN', 'LEOSA', 
                        'REKAR', 'SEVEN', 'BETA', 'VIIDIAN', 'BAHRAT',
                        'FROLA', 'MOSS', 'MOTHER', 'RESH', 'LORRUM',
                        'MORAK', 'CO', 'KORU', 'CAVIT', 'NEWTON',
                        'RINNA', 'DALA',  'SHOPKEEPER', 'NOCONA', 
                        'SAAVDRA', 'TOLEN', 'GOTANA', 'SOH', 
                        'LIRIA',  'ENSIGN SAMANTHA WILDMAN',
                        'GOTH', 'MALICIA', 'COSIMO', 'ANKARI', 
                        'TELFER', 'BOMB/EMH', 'ALICE','SPECTRE', 
                        'EDITH', 'ENGINEER', 'GALEN', 'DIRECTION',
                        'THOMPSON','NOVAKOVICH',  'KADAN', 'CELES',
                        'DERETH', 'KUMAGAWA', 'HAYES',  'IKO', 'PILOT', 
                        'OFFICIAL', 'RENORA', 'NEWSREADER', 'VALEN',
                        'ALCIA', 'FRANNIE', 'ASSISTANT', 'BENAREN', 
                        'JAFFEN', 'DEVORE', 'JARLETH',  'LILLIAS',
                        'ARRIDOR', 'CLERIC', 'RICKY', 'TEERO',
                        'RAKOSAN', 'SHANNON', 'TOSIN', 'LORIA',
                        'MOTURA', 'FLOTTER', 'LAYNA', 'HALEY', 
                        'ZAHIR', 'KYMBLE', 'COMMANDER', 'DEMMAS',
                        'ENGINEERS', 'NAUSICAAN', 'PRAY', 'NAROQ', 
                        'DEXA', 'GUL', 'CREWMEN', 'BURKE', 'JIPPEQ', 
                        'CREWMAN', 'PRIME', 'SALVAGE SELLER', 
                        'GATH', 'KATIE', 'ARBITRATOR', 'PRISONER',
                        'LAXETH', 'VERIN', 'DREADNOUGHT', 'SUDER',
                        'TIMOTHY', 'ALPHA', 'AMERON', 'ENTITY',
                        'INDIGENOUS PERSON', 'PORTER', 'OCLARE',
                        'NOONAN', 'ZET', 'HAWKINS', 'TEREK', 
                        'TIERNA',  'TABRIS', 'DUCANE', 'PELK',
                        'OREK', 'JARVIN', 'KAL', 'BORG QUEEN', 
                        'ALMAK', 'MENDEZ', 'DRONE', 'RUK', 'PRAX',
                        'KOHLAR', 'PCHAKOTAY', 'ADULTERESS',
                        'GAUMAN', 'MAGNUS', 'KOL', 'GARON', 'ORDERLY',
                        'LOTH', 'MASTER', 'LINNIS',  'PAXIM', 'MARNA',
                        'KIM', 'KANG', 'CAMERON', 'LANG', 'CONSUL', 
                        'OWEN', 'PSEVEN', 'NAVIGATOR', 'ODALA', 'BRAX',
                        'TREEN', 'FATHER', 'EMIL', 'NOISE', 'AXUM', 
                        'JOHN', 'NEVALA', 'TERLA', 'KING', 'JAL', 'KORTAR',
                        'HIJQA', 'JOLEG', 'CHANCELLOR', 'TOMMY',
                        'BORG', 'PKIM', 'PAH', 'COUNSELOR DEANNA TROI',
                        'CROWD', 'BROHT', 'REGINALD BARCLAY', 'DAYLA', 
                        'SAOWIN', 'MINER', 'AYALA', 'JESSEN', 
                        'ANNIKA HANSEN (SEVEN OF NINE)','HATIL', 'BUTCH', 
                        'KELEMENE', 'BARUS', 'OCAMPA', 'ALIEN', 'LASCA', 
                        'DALBY', 'KATANAY', 'HALIZ', 'DEMONICA', 'OTHERS', 
                        'ALLOS', 'TALLI',  'CHIEF', 'DUMAH', 'KOROK',
                        'TORREY', 'BAJORAN', 'PHYSICIAN', 'TEMBIT', 'JARYN',
                        'KURROS', 'ABARCA', 'DATHAN', 'QUARK',  'DANARA',
                        'GHANDI', 'PULL', 'JISA', 'ECO', 'EMH2', 'LANA', 
                        'STADI', 'GARRISON', 'ADMIRAL PARIS', 'PRICE', 
                        'ENSIGN LINDSAY BALLARD', 'NIGHT', 'BELLE',
                        'RICE', 'PHASER', 'KELLAN', 'BROKTAN', 'VALTANE',
                        'ALBEN', 'LARG', 'RAFIN', 'LAFORGE', 'KERIN',
                        'HARKINS', 'CARETAKER', 'HANSON', 'FLORA',
                        'DYSEK', 'VRELK', 'PUT', 'VATM', 'CORIN',
                        'TALAXIAN', 'KASHYK', 'BRIN', 'SURGEON',
                        'MIRAL', 'BURKUS', 'FEMALE', 'SILVER BLOOD NEELIX', 
                        'DEPUTY', 'NEELIX',  'DANNY', 'MOBAR', 
                        'SILVER BLOOD CHAKOTAY', 'SILVER BLOOD BELANNA', 
                        'SILVER BLOOD HARRY KIM', 'FUTURE CAPTAIN LAFORGE', 
                        'ADMIRAL JANEWAY', 'SILVER BLOOD TOM PARIS', 
                        'SILVER BLOOD SEVEN OF NINE', 'SILVER BLOOD EMH', 
                        'EMH (EMERGENCY MEDICAL HOLOGRAM MARK ONE)',
                        'TOWNSPERSON', 'BOY', 'KAR', 'JARLATH', 'ARTURIS',
                        'SILVER BLOOD TUVOK', 'OWNER', 'LOUIS ZIMMERMAN',
                        'HICKMAN', 'STOWAWAY', 'DAD', 'JIM', 'GINSBERG',
                        'YIFAY', 'IRINA',  'MICHAEL', 'EMCK', 'GREEN', 
                        'SILVER BLOOD JANEWAY', 'YOSA', 'GIGOLO', 'YERID',
                        'MAGISTRATE', 'ABBOT', 'FESEK', 'HENRY',  'HUMAN',
                        'MILO', 'DAVIS', 'TULAK', 'GERMAN', 'DOCTOR', 'SESKA',
                        'NICOLE', 'HARON', 'KLINGONS', 'CAPTAIN BRAXTON', 
                        'BRONE', 'HANJUAN',  'POLICE', 'AMBASSADOR',
                        'BENNET', 'GAUL', 'GAR', 'TABOR', 'JONES',
                        'MAXWELL', 'GENNARO', 'BILLY','VIORSA'], 
                        'ENT': ['THALEN', 'GORN', 'HUMANOID',
                        'GEORGIA', 'DRENNIK', 'KLINGON', 'MAGGIE',
                        'RAJIIN', 'KLAANG', 'WILLIAM RIKER', 
                        'COCHRANE', 'TPOL1', 'OFF', 'DEEAHN', 'BECKY',
                        'PRESSMAN', 'GRALIK', 'TREVIX', 'IKARA', 'ROCK', 
                        'PRESAGE', 'PIERCE', 'GOFF', 'KRAUL', 'TRAVIS',
                        'EZRAL', 'GHRATH', 'COMM',  'BOK', 'RAMIREZ',
                        'DANIELS', 'TARQUIN', 'YEDRIN', 'DAMRON',
                        'GURI', 'LATRELLE', 'PRISONERS', 'CRATER',
                        'THOLIAN', 'RIANN', 'TARKALEAN', 'JOE', 
                        'TACTICAL OFFICER', 'JOSIAH', 'FRADDOCK', 'RAT',
                        'RIVERS', 'VULCAN', 'AHLEN', 'LUCAS', 'TUCKER',
                        'GOSIS', 'DRAT', 'GRAL', 'GAROS', 'JENKINS',
                        'BEING', 'WOMAN', 'MONINGER', 'SOUNDS', 'SLAR',
                        'YOLEN', 'KUVAK', 'ADMINISTRATOR', 'KREETASSAN',
                        'COLONEL', 'GREER', 'FRESH', 'GANNET', 'ELIZABETH',
                        'GOSS', 'TELLUS', 'PAXTON', 'SUB COMMANDER', 'MARY', 
                        'SOVAL', 'ROMULAN', 'ZEPHT', 'VALDORE',
                        'SAJEN', 'ALISON', 'CARLOS', 'HELMSMAN', 
                        'TPOL2', 'BAIRD', 'DURAS', 'JEFFREY', 'COMPUTER',
                        'TEACHER', 'SULIBAN', 'GREAVES','STABLEHAND',
                        'ALICIA', 'KESSICK', 'SIM', 'SONSORRA', 'GAAVRIN',
                        'GRAT', 'BLACK', 'GARDNER', 'CREWWOMAN',
                        'STRON', 'SECURITY', 'TEMEC', 'RAAKIN', 'COGENITOR',
                        'ZHOKAAN', 'AREV', 'KVAGH', 'MAJOR', 'KREM', 
                        'SAMUELS', 'TECHNICIAN', 'MOORE', 'SHAW',
                        'SLAVER', 'HELM', 'BACK', 'SPACE', 'LEONARD',
                        'LIANA', 'ZSHAAR', 'HOSHI', 'YARRICK', 'HARRIS',
                        'MENOS', 'HEAD', 'MISTRESS', 'MARAB', 'ROSTOV',
                        'SOONG', 'LIEUTENANT', 'MITCHELL', 'TOLARIS',
                        'GUARD', 'CHESTER', 'MALIK',  'JAMIN',  'LOOMIS', 
                        'HUDAK', 'HARRAD', 'OFFICER', 'MACO', 'ETHAN',
                        'COLLINS', 'QUINN', 'ENSIGN', 'WILLIAMS', 
                        'MAYA', 'MAN', 'DANICA', 'LORIAN', 'MARK', 
                        'PERSIS', 'TAVIN', 'TNAR', 'FIRST', 'VOSK',
                        'HAWKINGS', 'MUROC', 'ORGOTH', 'VANIK', 'DJAMAT', 
                        'ZOUMAS', 'KRIOS', 'JAREB', 'MEDIC', 'THREE',
                        'STEL', 'ORION', 'PRIEST','CAPTAIN', 'KAITAAMA',
                        'SWITCH', 'SAL', 'GENERAL', 'STROMM',  'SOLDIER',
                        'BUILDER', 'CALLA', 'TPOL', 'SCIENTIST', 'DILLARD',
                        'HARRY', 'VOICES', 'DOCKMASTER', 'NARRA', 'KOSS',
                        'LA', 'NIJIL', 'HER', 'TALAS', 'GOVERNOR',
                        'KELLY', 'AIDE', 'DEGRA', 'SENATOR', 'TRENAL',
                        'RENTH', 'NORA', 'COLE',  'INSECTOID', 'MAZARITE',
                        'BARBER', 'TALLA', 'TRET', 'TALIYAH', 'JANNAR',
                        'CARMINE', 'ENOLIAN', 'JEAN', 'EMORY', 'TAGRIM', 
                        'THOLOS', 'THUG', 'GOROTH', 'ORAK', 'TARAH',
                        'RAVIS', 'LANETH', 'INDAVA', 'MACCREADY',
                        'TELLARITE', 'RESEARCHER', 'MOTHER', 'PHLOX', 
                        'PICARD', 'CHARLIE',  'KLEV', 'PILOT', 'XANTORAS', 
                        'ZOBRAL', 'PAUL', 'SMIKE', 'RYAN', 'SOLDIERS',
                        'ENGINEERING', 'NAVAAR', 'SHRAN', 'JACK',
                        'DRAYSIK', 'ERIKA', 'ENGINEER', 'FERAT',
                        'BRAT', 'TAYLOR', 'GAREB', 'PELL', 'MCKENZIE',
                        'HAYES', 'OFFICIAL', 'SARIN', 'RAAN',  'WITCH', 
                        'BENNINGS', 'XINDI', 'NADET', 'PLINN',
                        'KARYN', 'STUDENTS', 'ELDER', 'BARKEEP',
                        'TROI', 'COMMANDER', 'HIM', 'NAUSICAAN', 'ATHAN',
                        'RIANNA', 'MESTRAL', 'CREWMAN', 'PRIME', 'GRISH',
                        'REPTILIAN', 'TRELLIT', 'ULIS', 'ARBOREAL', 'DRAKE',
                        'HAWKINS', 'DNESH', 'KAGO', 'GIRL',  'SILIK',
                        'DATA', 'MUK', 'RECEPTIONIST', 'CORIDAN', 'NAARG',
                        'ROONEY', 'TMIR', 'ROBINSON', 'MASARO', 'FEEZAL',
                        'KHOURI', 'SOPEK', 'NALBIS', 'TLES', 'MASTER',
                        'LOKESH', 'STABLE', 'RISAN', 'JUAN',  'VEYLO',
                        'SHILAT', 'VLAR', 'FATHER', 'EMIL', 'TRAEG',
                        'FLIGHT', 'JOHN', 'PRISONER', 'TPAU', 'JHAMEL',
                        'ILLYRIAN', 'BETHANY','LISSAN', 'TOMMY', 'CUTLER',
                        'SLOTH', 'HAMLET', 'PALANTI',  'SEX WORKER',
                        'VLAS', 'BARTENDER', 'KRELL', 'CHANCELLOR', 
                        'ADMIRAL', 'AMANDA',  'SKALAAR', 'DMARR', 
                        'JEREMY', 'MADELINE', 'PADD', 'VRAX', 'MINER',
                        'AQUATIC2', 'ALIEN', 'SATO', 'MANTOOS', 'KUULAN',
                        'WALSH', 'FALL', 'ARCHER', 'PULL', 'REED', 'KEYLA',
                        'NIGHT', 'AKARY', 'NAH', 'LATIA', 'KEENE', 'CERIS',
                        'CUNNINGHAM', 'DEPUTY', 'HEAR',  'SHIRAHT',
                        'SURAK', 'PUT', 'TAVEK', 'KELBY', 'MAY', 'FORREST', 
                        'KOLOS', 'CHIEF', 'BOY', 'JONATHAN', 'DANIK', 'RUBY',
                        'ANTAAK', 'FOREMAN', 'DOLIM', 'BUSINESSMAN',
                        'CHANG', 'YURIS', 'DAMRUS', 'BUKAH', 'MAGISTRATE',
                        'KEVAL', 'TALOK', 'MADISON', 'GERMAN',
                        'BURZAAN', 'KURODA', 'HENRY', 'TELEV', 'ORATT', 
                        'VOROK', 'HUMAN', 'KLINGONS', 'BILLY',
                        'ZJOD', 'KEMPER', 'AMBASSADOR', 'MAXWELL'],
                  'DSC': ['PRIMARY', 'GIOTTO', 'PAUL STAMETS', 
                        'ASH TYLER', 'BRIANNA', 'ADIRA TAL', 
                        'KLINGON', 'PATIENT', 'OWOSEKUN','LIDO', 
                        'GEORGIOU', 'TEEMO', 'BETA', 'CAPTAIN SARU',
                        'THE GUARDIAN OF FOREVER', 'SPOCK', 'AI',
                        'LAI', 'TELLARITE', 'VOS', 'SIRANNA','MANN', 
                        'CARA', 'AN ALIEN', 'FIRST OFFICER SARU', 
                        'SECURITY OFFICER NHAN', 'RYN', 'ZAREH', 
                        'LINUS THE LIZARD', 'OPS OFFICER', 'NRAJ', 
                        'ENGINEERING OFFICER', 'OTHERS', 'AIRIAM',
                        'CAPTAIN CHRISTOPHER PIKE', 'OSSYRA', 
                        'VIC', 'KANAK', 'LIEUTENANT', 'KOVICH', 
                        'TACTICAL OFFICER', 'CLEVLAND BOOKER (BOOK)', 
                        'SAHIL', 'GUARD', 'DOCTOR ISSA HOLOGRAM',
                        'REGULATOR', 'PYSCHIATRIST', 'ENGINEER', 
                        'OFFICER', 'SHIRA', 'LRELL', 'CREW', 'DOT',
                        'HELMSMAN KEYLA DETMER', 'BAUL','OSYRAA', 
                        'VULCAN', 'OFFICIAL', 'KYHEEM',  'TRINA',
                        'GARRISON', 'ADMIRAL', 'ENSIGN', 'TALOSIAN', 
                        'MIRROR HUGH CULBER',  'HARRY MUDD', 
                        'MIRROR PAUL STAMETS', 'MIRROR SARU',
                        'MIRROR KEYLA DETMER', 'MIRROR BRYCE',
                        'MIRROR DOCTOR POLLARD', 'TKUVMA',
                        'CAPTAIN LORCA', 'EMPEROR GEORGIOU', 
                        'CAPTAIN GEORGIOU',  'STELLA MUDD', 
                        'ADMIRAL KATRINA CORNWELL', 'ELLEN LANDRY', 
                        'KAMARAN GANT', 'BRITCH WEETON', 
                        'JOANN OWOSEKUN', 'R. A. BRYCE', 'CARL', 
                        'GEN RHYS', 'OSNULLUS', 'AMANDA GRAYSON',
                        'NUMBER ONE', 'UNA', 'YEOMAN COLT', 
                        'CLINT HOWARD', 'UJILI', 'ADITYA SAHIL',
                        'SENNA TAL', 'TROY JANUZZI', 'COLD',
                        'AUDREY WILLA', 'DANABY CONNOR', 
                        'AURELLIO', 'ADMIRAL TERRAL',  'TOLOR', 
                        'TELLARITE ADMIRAL', 'ADMIRAL GORCH', 
                        'ZORA', 'MILTON RICHER', 'DENNAS', 
                        'BRETT ANDERSON', 'NICOLA', 'CONNOLLY', 
                        'CAPTAIN MADDOX', 'ERTOOM',  'DOCTOR ATTIS', 
                        'COMMISONER VOS', 'ZAREH', 'THE KEEPER', 
                        'ADMIRAL PATAR', 'TRILL LEADER PAV', 
                        'PRESIDENT TRINA', 'TEEMO', 'AMIN', 
                        'JACOB', 'WEN', 'BARON GRIMES', 'STRAAL', 
                        'ITHYK THE ANDORIAN', 'CAPTAIN NDOYE',
                        'KOVIL', 'KYHEEM', 'ITHOR', 'DUGGAN', 
                        'ENGINEER RANCE', 'BARLOW', 'STONE',
                        'BETARIAN GIRL', 'NRAJ', 'VLATAK',
                        'RED EYES',  'SHAVO',  'SHIRA','MANN', 
                        'REJAC', 'SHUTTLE PILOT', 'STEPHEN', 
                        'ROSE', 'ALIEN MERCHANT', 'KANAK',
                        'KAL', 'CREPUSCULA', 'ADMIRAL DRAKE', 
                        'CAPTAIN DEIGO VELA', 'AMBASSADOR SAREK',
                        'BEING', 'MIRROR MICHEAL BURNHAM',
                        'HAJ', 'OSIR', 'WEAPONS TRADER', 
                        'HELMENT COMPUTER', 'CONTROL COMPUTER', 
                        'DISCOVERY COMPUTER', 'CONTROL', 
                        'REGULATOR', 'ENSIGN HAZMAT', 'LETO', 
                        'LAI', 'AVYRZ', 'SHAVA', 'MAN',
                        'CAPTAIN LTEIS', 'KVORT', 'BANDRA', 
                        'TRILL', 'DOCTOR HUGH CULBER','COSMO',
                        'KELPIEN', 'BRYCE', 'PHILLIPA GEORGIOU', 
                        'VINA', 'PREACHER', 'OPERATIVE', 
                        'ADMIRAL CHARLES VANCE', 'CHIEF', 
                        'ELDER KELPIEN', 'ENGINEER JET RENO', 
                        'MIKE', 'GRAY TAL', 'AVRYZ', 'BEN',
                        'SYLVIA', 'COMMANDER', 'ITHOR', 
                        'MAY', 'NURSE', 'WEN', 'KOLSHA', 
                        'QUEEN ME HANI IKA HALI KA PO', 
                        'MONSTER', 'GRUDGE', 'BOY', 'CHILDREN', 
                        'MIRROR RHYS','KILLY', 'MIRROR OWOSEKUN',
                        'CREWMAN', 'COMMANDER MICHEAL BURNHAM', 
                        'CHILD', 'ORION', 'TILLY',   'SERVANT',
                        'ELI', 'GENERAL', 'CAPTAIN', 'CARL',
                        'CAPTAIN LELAND','CONTROL LELAND'
                        'HOLO', 'CONTROL', 'RHYS', 'MOLLY',
                        'TENAVIK', 'KAL', 'GABRIELLE BURNHAM', 
                        'FIGURE', 'NILSSON', 'ROBOT', 'ATTIS',
                        'DOCTOR TRACY POLLARD', 'PERSONNEL', 
                        'NAHN', 'STAGE', 'COMPUTER', 'VKIR', 
                        'TOLOR', 'DOCTOR', 'KOL', 'NICOLA', 
                        'DUGGAN', 'SUKAL', 'KLINGONS', 'APRIL',
                        'SECURITY', 'AMBASSADOR', 'HADLEY', 
                        'PATAR', 'VELA'],
                  'PIC': ['EMERGENCY NAVIGATIONAL HOLOGRAM', 'EMIL', 
                          'COMMODORE/ROMULAN COMMANDER OH', 
                          'INTERFACE', 'DAHJ ASHA', 'DOCTOR SOJI ASHA', 
                          'SEVEN OF NINE (ANNIKA HANSEN)', 'SUTRA', 
                          'ZANI', 'LEIUTENANT NARISSA RIZZO', 'SAGA', 
                          'BORG', 'ELNOR', 'ADMIRAL JEAN LUC PICARD',
                          'BJAYZL', 'CAPTAIN CHRISTOBAL RIO', 'BETA',
                          'COUNSELOR DEANNA TROI',  'RAFFI MUSIKER', 
                          'ANNIKA HANSEN (SEVEN OF NINE)','AI', 
                          'PINCUS', 'ENGINEERING OFFICER', 'RAMDHA', 
                          'MOTHER', 'DAHJS BOYFRIEND', 'ADMIRAL CLANCY', 
                          'XB WORKER', 'RUNE', 'CODEX', 'ARCANA', 'SAGA', 
                          'RELLARITE', 'XB', 'DOCTOR MORITZ BENAYOUN', 
                          'INTERVIEWER', 'GABRIEL HWANG', 'EMMY', 
                          'CHOP DOC', 'DOCTOR KABATH', 'INDEX', 
                          'PEL', 'YOUNG SOJI', 'TAL SHIAR FEMALE',
                          'TENQEM ADREV', 'BIDRAN', 'OLDER XB',
                          'TAL SHIAR OPERATIVE', 'WAITER', 'MR VUP',
                          'ROMULAN GAURD', 'BURLEY FUIELIE', 'NAREK', 
                          'SKANTAL', 'F8', 'KIBITZER','GAURD', 
                          'ADMIRAL WILLIAM RIKER','BARTENDER',
                          'OTHERS', 'PINCUS', 'ENSIGN', 'NOIRO',
                          'DOCTOR ALTAN INIGO SOONG', 'LIEUTENANT', 
                          'ZHABAN', 'WOMAN', 'ICHEB', 'RICHTER', 
                          'EMMY', 'OFFICIAL', 'ANDREV', 'HUGH',
                          'BOLIAN', 'VUP', 'KESTRA', 'COMMANDER', 
                          'EMERGENCY MEDICAL HOLOGRAM (RIO)',
                           'SHAI', 'Q', 'GABRIEL', 'GUARD', 
                          'RIZZO', 'GENERAL', 'DATA',  'IAN',
                          'CREWMAN', 'THREE', 'KESTRA', 'LARIS',
                          'ROMULAN', 'CAPTAIN', 'ARCANA', 'QUEEN', 
                          'ANDROIDS', 'ROBOT',  'GAURD', 'KABATH', 
                          'LOCUTUS', 'RAMDHA','POLICEMAN', 'FEMALE', 
                          'COMPUTER', 'EMMOT', 'BRUCE MADDOX',
                          'DOCTOR AGNES JURATI', 'HUMAN', 
                          'SECURITY OFFICER', 'EMMET','CALER', 
                          'MALE', 'ATTENDANT', 'ADMIRAL'],
                  'LD' : ['CHEIF OF SECURITY LIEUTENANT SHAXS', 
                        'MEDICAL ENSIGN DVANA TENDI', 'PAKLEDS', 
                        'CHEIF MEDICAL OFFICER DOCTOR TANA','ROGA',
                        'KING', 'ENSIGN BARNES', 'SEVEN', 'GUARDS', 
                        'BETA', 'COMMAND ENSIGN BECKETT MARINER', 
                        'LIEUTENANT WINGER BINSTON JR', 'ENSIGN JEN', 
                        'BADGEY', 'ENSIGN FLETCHER', 'ALIEN', 
                        'LIEUTENANT COMMANDER STEVENS','A KLINGON',
                        'ADIRMAL VASSER', 'CAPTAIN DAYTON', 'DURGAN', 
                        'BORG', 'MIGLEEMO', 'CAPTAIN WILLIAM RIKER', 
                        'COMMMAND ENSIGN BRAD BOIMLER', 'HOLD', 'NIKO', 
                        'ENGINEERING', 'OPS', 'KLINGON GENERAL KORIN', 
                        'BAJORAN', 'WINGER', 'LIEUTENANT', 'SHEMPO', 
                        'ENGINEERING ENSIGN SAMANTHAN RUTHERFORD', 
                        'ENGINEER', 'STEVENS', 'WARREN','FERENGI', 
                        'OFFICER', 'INSECT', 'ADMIRAL', 'ANABAJ', 
                        'ENSIGN', 'VENDOME', 'CARDASSIAN', 'Q',
                        'OCONNOR', 'ASIF', 'LEMONTS', 'JEN',
                        'WOMAN', 'FIRST OFFICER JACK RANSOM', 
                        'QUIMP THE FERENGI', 'COUNSELOR DEANNA TROI', 
                        'GALARDONIANS', 'NURSE WESTLAKE', 'LUNDY', 
                        'CAPTAIN CAROL FREEMAN','CAPTAIN DURANGO',
                        'ADMIRAL FREEMAN', 'CAPTAIN AMINA', 'CHIEF',
                        'CHEIF ENGINEER ANDY BILLUPS','COMMANDER', 
                        'SHAPESHIFTER', 'BOY', 'CREWMAN', 'PRIME', 
                        'JET', 'GENERAL', 'ROMULAN', 'CAPTAIN',
                        'GALRAKIAN', 'VASS','SECURITY OFFICER', 
                        'HOLODECK PROGRAM MARINER','LANDRU',
                        'DIVISION 41 OFFICER','PEANUT HAMPER'
                        'PRACHETT', 'COMPUTER', 'TEACHER', 
                        'DAYTON', 'HUMAN', 'HALFOLD', 'THE DOG', 
                        'ENERGY', 'VINDOR', 'CLAR', 'ATTENDANT',
                        'STEVE', 'AN UNKNOWN ENTITY']
                  }
